name: Validations

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: SQL Lint

    steps:
      - uses: actions/checkout@v4

      - uses: Bidaya0/sql-lint-in-action@v0.0.3
        with:
          path: "${{ github.workspace }}/src"
