name: Validations

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: SQL Lint

    steps:
      - uses: actions/checkout@v4

      - uses: Bidaya0/sql-lint-in-action@v0.0.1
        with:
          paths: "${{ github.workspace }}/src"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
