name: Validations

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: SQL Validations

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: cideades_e_estados
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_DATABASE: cideades_e_estados
      DB_USER: root
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - name: run SQL with no errors
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS cideades_e_estados;' -u${{ env.DB_USER }}
          mysql --default-character-set=utf8 cideades_e_estados < src/cidades-e-estados.sql -u${{ env.DB_USER }} 
          mysql -e 'USE cideades_e_estados; DROP TABLE cidades; DROP TABLE estados;' -u${{ env.DB_USER }} 
          mysql --default-character-set=utf8 cideades_e_estados < src/estados.sql -u${{ env.DB_USER }} 
          mysql --default-character-set=utf8 cideades_e_estados < src/cidades.sql -u${{ env.DB_USER }}
