name: Validations

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  sql:
    runs-on: ubuntu-latest
    name: SQL Validations
   
    env:
      DB_DATABASE: cideades_e_estados
      DB_USER: root
      DB_PASSWORD: rootpassword

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{env.DB_DATABASE}}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: run SQL with no errors
        run: |
          mysql -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS ${{env.DB_DATABASE}};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -h 127.0.0.1 --default-character-set=utf8 ${{env.DB_DATABASE}} < sql/cidades-e-estados.sql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} 
          mysql -h 127.0.0.1 -e 'USE ${{env.DB_DATABASE}}; DROP TABLE cidades; DROP TABLE estados;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} 
          mysql -h 127.0.0.1 --default-character-set=utf8 ${{env.DB_DATABASE}} < sql/estados.sql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} 
          mysql -h 127.0.0.1 --default-character-set=utf8 ${{env.DB_DATABASE}} < sql/cidades.sql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  json:
    runs-on: ubuntu-latest
    name: JSON Validations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Lint JSON files
        run: |
          for file in $(find ./json -name "*.json"); do
            echo "Checking $file"
            jq empty "$file" || exit 1
          done
